"""Generate METHODOLOGY.md from live values so it cannot drift from what the system does."""
import datetime as dt
from typing import Dict

from pipeline import config

TEMPLATE = """# Methodology

This file is generated by pipeline/methodology.py from live values at export
time. Do not edit it by hand; edit the generator or the configuration it reads.

Generated {generated_at}. Ruleset version {ruleset_version}. Schema version {schema_version}.

## What the system does

Every hour it polls the RSS feeds of every active outlet in sources/outlets.yaml,
stores every item before doing anything else, and applies a loose multilingual
keyword gate to the title and summary to decide whether an item plausibly
concerns China. Items that pass the gate are fetched in full, honoring
robots.txt, at most one request per domain every three seconds, with an
identifying user agent. Pages that declare themselves not free in schema.org
metadata, or that present a paywall interstitial with a short body, are
recorded as paywalled and never retrieved by any other route.

Fetched articles pass through a deterministic signature matcher
(pipeline/signatures.yaml) that detects state origin text by credit lines, datelines,
distribution stamps, sponsored placement disclosures and diplomatic bylines.
Any strong signature, or weak signatures from two different groups, gives
the state origin label with confidence 1.0 and no model call. One weak signature, or any
official sourcing trigger (a citation of Xinhua, CGTN, Global Times, China
Daily, CCTV or People's Daily; a quoted Ministry of Foreign Affairs
spokesperson, Chinese embassy or named official spokesperson; or a
"state media reported" construction in any registry language), routes the
article to a language model for the unverified relay versus independent
journalism judgement. Articles with no
signature and no trigger are labelled independent journalism by rules when
the body mentions at least three distinct China terms, otherwise not relevant. Those residual
labels carry confidence below 1.0 and are sampled by the agreement study like
every other label.

The model ({llm_model}) sees the headline and body only. It never sees the
outlet name or the country, so it cannot learn that outlets in particular
countries tend to relay official sourcing. Its prompt contains the category
definitions verbatim and instructs it to answer independent journalism when
genuinely uncertain, because under-counting unverified relay is the safer error.

The instrument exists to find two kinds of article: state placements and
local pieces that carry Chinese official or state media claims without
checking them. Ordinary China coverage is only the denominator. Articles whose
official sourcing has been detected but whose verification judgement has not
yet run are reported separately as candidates, never folded into either label.
At export time {pending_n} such candidates were waiting across {pending_countries}
countries.

## The categories

State origin. {cat_a}

Unverified relay. {cat_b}

Independent journalism. {cat_c}

Not relevant. {cat_n}

The critical distinction is between unverified relay and independent
journalism, and it is a judgement about verification, not about topic or tone.
An article highly critical of China that repeats an unverified Xinhua claim is
still unverified relay. An article sympathetic to China that independently
confirms every claim is independent journalism. In the database and the data
files these four labels are stored as the codes A, B, C and not_relevant, in
that order, for compactness; the interface never shows the codes.

## Current state

| Measure | Value |
| --- | --- |
| Outlets registered | {outlets_total} |
| Outlets active | {outlets_active} |
| Countries monitored | {countries_monitored} |
| Countries recorded as coverage gaps | {countries_in_gaps} |
| Articles discovered | {articles_discovered} |
| Articles passing the relevance gate | {articles_gate_relevant} |
| Articles classified | {articles_classified} |
| Articles with a human review | {articles_reviewed} ({review_coverage_pct} percent of classified) |
| Share of gated articles that were paywalled | {paywall_share_pct} |
| Countries flagged as not comparable because of paywalls | {paywall_flagged} |
| State origin, all time | {a_total} |
| Unverified relay, all time | {b_total} |
| Independent journalism, all time | {c_total} |
| Language model calls, all time | {llm_calls_total} |
| Days on which the model call ceiling ({llm_daily_ceiling}) was hit | {llm_ceiling_days} |
| Last successful run | {last_successful_run} |

## Agreement

{kappa_text}

## What the numbers mean

Share of monitored China coverage that is state origin or unverified relay is
the headline number. Raw
counts mostly measure how many outlets the registry happens to track in a
country. Articles per monitored outlet corrects for registry density.

Absence of data and absence of content are different things. A country with no
monitored outlets is drawn with a hatch pattern. A country with monitored
outlets and no detections is drawn flat. Only detections above zero use the
color scale. A country whose feeds are mostly failing, or whose articles are
mostly paywalled, carries a warning and its tooltip says why.

Near-duplicate titles within a country are linked as one underlying item.
They count as multiple placements, which is what the map shows, and the
number of underlying items is exported alongside.

## Reproducibility

Every classification row records the ruleset version and, for model labels,
the model version. When the signature list changes, the ruleset version is
bumped in pipeline/config.py, the change is recorded in CHANGELOG.md, and
articles are reclassified forward. Earlier rows are kept and marked not
current, so a chart made from the database at any date can be reproduced.
Human review labels are stored in a separate table and never overwrite
machine labels.

The database itself is not committed to git, because a growing SQLite file
exceeds GitHub's file size limit within weeks. It travels between runs
through the GitHub Actions cache and is snapshotted daily, compressed, as a
release asset. The permanent record in git is data/export, one JSON line per
gated article per month with its current classification, plus the site data
under docs/data. One deliberate exception to the never-delete rule: items the
relevance gate rejected are pruned after {retention} days, once they have
served the gate audit. They carry no classification.
"""


def write(meta: Dict, latest: Dict, path=config.ROOT / "METHODOLOGY.md") -> None:
    tot = latest["totals"]["all_time"]
    k = meta.get("kappa")
    if k and k.get("bc") is not None:
        settled = "Unverified relay counts are displayed as settled." if meta["b_counts_settled"] else (
            "Kappa on the unverified relay versus independent journalism distinction is below %.1f, so the interface does not display unverified relay counts as settled." % meta["kappa_warning_threshold"])
        kappa_text = ("The most recent agreement study (%s) hand coded %d machine labelled articles. Cohen's kappa "
                      "across all four categories is %.2f. Kappa on the unverified relay versus independent journalism distinction alone, computed over "
                      "the %d articles that either coder placed in one of those two, is %.2f. %s") % (
            k["computed_at"][:10], k["n"], k["all"] if k["all"] is not None else float("nan"), k["n_bc"] or 0, k["bc"], settled)
    else:
        kappa_text = ("No agreement study has been completed yet. Until one is, the interface labels unverified relay counts as "
                      "provisional. Run pipeline/agreement.py to draw a sample, hand code it, and compute kappa.")
    text = TEMPLATE.format(
        generated_at=meta["generated_at"], ruleset_version=meta["ruleset_version"], schema_version=meta["schema_version"],
        llm_model=meta["llm_model"],
        cat_a=meta["categories"]["A"], cat_b=meta["categories"]["B"], cat_c=meta["categories"]["C"], cat_n=meta["categories"]["not_relevant"],
        outlets_total=meta["outlets_total"], outlets_active=meta["outlets_active"],
        countries_monitored=meta["countries_monitored"], countries_in_gaps=meta["countries_in_gaps"],
        articles_discovered=meta["articles_discovered"], articles_gate_relevant=meta["articles_gate_relevant"],
        articles_classified=meta["articles_classified"], articles_reviewed=meta["articles_reviewed"],
        review_coverage_pct=round(meta["review_coverage"] * 100, 1),
        paywall_share_pct=("%.1f percent" % (meta["paywall_share"] * 100)) if meta["paywall_share"] is not None else "not yet measured",
        paywall_flagged=", ".join(meta["paywall_flagged_countries"]) or "none",
        a_total=tot["A"], b_total=tot["B"], c_total=tot["C"],
        llm_calls_total=meta["llm_calls_total"], llm_daily_ceiling=meta["llm_daily_ceiling"],
        llm_ceiling_days=", ".join(meta["llm_ceiling_days"]) or "none",
        last_successful_run=meta["last_successful_run"] or "none",
        pending_n=meta.get("official_sourcing_pending", 0), pending_countries=meta.get("official_sourcing_pending_countries", 0),
        retention=config.GATED_OUT_RETENTION_DAYS,
        kappa_text=kappa_text,
    )
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
